[TIP]
====
You can add child elements under this trust boundary by clicking one of the buttons below.

To add a data flow to or from this trust boundary, click the link symbol in the top level tool bar to create a link.
====

== Composite components

=== Trust boundary

A trust boundary is a boundary between different trust zone levels.

{{{createCards '{"buttonLabel": "Create a trust boundary", "template": "trustBoundary"}'}}}

=== External entity

An external entity is a source, from which information flows into the system, or a recipients of information leaving the system

{{{createCards '{"buttonLabel": "Create an external entity", "template": "external"}'}}}

=== Person

A person is a user, an administrator or another human stakeholder. A special case of an external entity.

{{{createCards '{"buttonLabel": "Create a person", "template": "person"}'}}}

=== Process

A process represents an activity that the system carries out.

{{{createCards '{"buttonLabel": "Create a person", "template": "process"}'}}}

=== Data store

A data store stores information. For example, a database or a file.

{{{createCards '{"buttonLabel": "Create a data store", "template": "dataStore"}'}}}

